//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserClass.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDb
    {
        public string PolicyName { get; set; }
        public string userEmail { get; set; }
        public decimal PolicyAmount { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
